## CHANGE this to the name of your plugin.
name: SFZM

## CHANGE this to your username.
author: zimzaza4


## CHANGE this to a meaninful but short description of your plugin.
description: A generic Slimefun4-Addon

## CHANGE this to the path of the class that extends JavaPlugin.
main: zim.wdnmd.slimefunaddon.ExampleAddon

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/zimzaza4/ZM

## This is required and marks Slimefun as a plugin dependency.
depend: [Slimefun]

## This value is automatically replaced by the version specified in your pom.xml file, do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.14
